# model_name_or_path: saves/gpt2/full/pretrain
# model_name_or_path: openai-community/gpt2
# model_name_or_path: meta-llama/Llama-3.2-1B
model_name_or_path: saves/llama/full/midtrain_wikitext
template: null
infer_backend: huggingface #choices： [huggingface, vllm]