### model
model_name_or_path: meta-llama/Llama-3.2-1B
trust_remote_code: true

### method
stage: pt
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
flash_attn: fa2

### dataset
dataset: wikitext
# template: llama3
cutoff_len: 512
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/llama/full/midtrain_wikitext_dispersion_test
logging_steps: 1
# save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb
run_name: llama-wiki-pretrain-dispersion

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 128
learning_rate: 1.0e-5
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_steps: 50
weight_decay: 0.01
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 5

### dispersion loss
dispersion: "infonce"  # or "hinge", "covariance"
dispersion_coeff: 0.1
dispersion_loc: "last"  # or "all"
dispersion_eval: true
